#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    ecup-sdc-web-80-http:
      entrypoints:
        - http-33000
      rule: HostRegexp(`^ecup-sdc\.ddev\.site$`)
      
      service: "ecup-sdc-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ecup-sdc-redirectHttps"
    ecup-sdc-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^ecup-sdc\.ddev\.site$`)
      
      service: "ecup-sdc-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "ecup-sdc-redirectHttps"
    
    
    
    ecup-sdc-web-80-https:
      entrypoints:
        - http-33001
      rule: HostRegexp(`^ecup-sdc\.ddev\.site$`)
      
      service: "ecup-sdc-web-80"
      ruleSyntax: v3
      
      tls: true
      
    ecup-sdc-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^ecup-sdc\.ddev\.site$`)
      
      service: "ecup-sdc-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    ecup-sdc-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    ecup-sdc-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-ecup-sdc-web:80
        
    ecup-sdc-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-ecup-sdc-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/ecup-sdc.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/ecup-sdc.key